### ISSUE TITLE
furo install in BEC does not work (anymore)

### ISSUE THREAD

**Issue by thesse1** [eclipse/eclipsefuro#19]
When I run the instructions in the [Furo Quickstart Guide](https://furo.pro/docs/guides/quickstart/), I am getting the error message `git@github.com: Permission denied (publickey)` when I run `furo install`. This is caused by a new security restriction of GitHub requiring a registered public key for SSH connections. Follow GitHub's instructions for [generating an SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) and for [adding the key to your GitHub account](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account). After that, `furo install` is working fine. You might also be able to bind the user's existing SSH key in the host environment into the Docker container. I have not tried that out.

You should either include this in the Quickstart Guide itself, or you should include some default SSH key in the BEC. Or maybe you can rewrite `furo install` in such a way that it does not depend on SSH key in the container?

**Comment by veith** [comment]
@thesse1 Thank you for the hint.

**Comment by veith** [comment]
@maltenorstroem 
I updated the documentation and will register an issue in the quick start guide.

https://furo.pro/docs/tools/BEC/
