### ISSUE TITLE
Furo Flow Based Programming, Documentation

### ISSUE THREAD

**Issue by maltenorstroem** [eclipse/eclipsefuro#3]
Migration and revision of the Furo FBP Documentation.

> Introduction to Furo Flowbased Programming #
Write your applications like you make the concept for your application. Normaly you draw a few components and some arrows to connect the components, to describe your intention. Why you don’t do the same to write your app or component? Use existing web-components and wire them to build your application.

Publication: _fpb.furo.pro_

**Comment by veith** [comment]
@maltenorstroem Can you read the docs and tell me if it is clear enough please.

**Comment by veith** [comment]
This will be a continuous task...
